To select candidates for interviews and to get an overview of edits to the english language wikidata and bot participation, we gathered data from the January 6 United States Capitol Attack (J6USCA) wikidata revision history page.

In [1]:
import requests
import pandas as pd
import time
from datetime import datetime

In [2]:
#January 6 Capitol Attack ID
J6USCA_ID = "Q104705419"
#API
API_URL = "https://www.wikidata.org/w/api.php"

#fetch revision history
def get_edits(item_id):
    edits = []
    rvcontinue = None
    ok = True
    
    while ok:
        params = {"action": "query", "format" : "json", "prop": "revisions", "titles": item_id, "rvlimit": "max", "rvprop": "ids|timestamp|user|comment|flags|size"}
        
        if rvcontinue:
            params["rvcontinue"] = rvcontinue
            
        #retrieve from wikidata
        response = requests.get(API_URL, params = params, headers = {"User-Agent": "GetEditDataResearch"})
        if response.status_code == 429:
            print("sleep 5")
            time.sleep(5)
        response.raise_for_status()
        data = response.json()
        
        pages = data["query"]["pages"]
        
        #get info from all recision history pages
        for page in pages.values():
            edits.extend(page.get("revisions", []))
            
        if "continue" in data:
            rvcontinue = data["continue"]["rvcontinue"]
        else:
            break
            
    return edits

revisions = get_edits(J6USCA_ID)

print(revisions)

[{'revid': 2504691802, 'parentid': 2503966829, 'user': 'Vicarage', 'timestamp': '2026-06-11T17:20:01Z', 'size': 167005, 'comment': '/* wbremoveclaims-remove:1| */ [[Property:P625]]: 38°53\'23"N, 77°0\'33"W, QuickStatements 3.0 [[:toollabs:qs-dev/batch/35934|batch #35934]]'}, {'revid': 2503966829, 'parentid': 2503943744, 'user': 'Vicarage', 'timestamp': '2026-06-09T21:04:25Z', 'size': 167520, 'comment': '/* undo:0||2503647430|Quesotiotyo */ Events clearly can have co-ordinates, removing them breaks lots of Wikipedia templates. User refused to engage even when asked repeatedly on talk ([[:toollabs:editgroups/b/EG/9c82e31|details]])'}, {'revid': 2503943744, 'parentid': 2503647430, 'user': 'Pi bot', 'timestamp': '2026-06-09T20:04:46Z', 'size': 167005, 'comment': '/* wbsetclaim-create:2||1 */ [[Property:P625]]: 38°53\'23"N, 77°0\'33"W, Importing coordinate from enwp'}, {'revid': 2503647430, 'parentid': 2500170824, 'user': 'Quesotiotyo', 'timestamp': '2026-06-09T06:11:24Z', 'size': 166474, 'comment': '/* wbremoveclaims-remove:1| */ [[Property:P625]]: 38°53\'23"N, 77°0\'33"W, #quickstatements; #temporary_batch_1780981630519; property is not to be used on events (these belong to the location (P276) instead)'}, {'revid': 2500170824, 'parentid': 2499912567, 'user': 'Twofivesixbot', 'timestamp': '2026-05-31T15:55:23Z', 'size': 167006, 'comment': '/* wbsetclaim-update-qualifiers:1||1|2 */ [[Property:P8189]]: 987011253755805171, mv to monolingual text names on J9U statements'}, {'revid': 2499912567, 'parentid': 2483947620, 'user': 'Diebu', 'timestamp': '2026-05-31T05:55:08Z', 'size': 166335, 'comment': '/* wbsetdescription-set:1|de */ gewaltsamer Angriff auf das Kapitol durch Anhänger Donald Trumps am 6. Januar 2021'}, {'revid': 2483947620, 'parentid': 2478517786, 'user': 'VGMaintenanceBot', 'timestamp': '2026-04-22T17:20:29Z', 'size': 166369, 'comment': '/* wbsetqualifier-add:1| */ [[Property:P9675]]: 131190, Add qualifier to WikiKids ID `Bestorming_van_het_Amerikaanse_Capitool_in_2021`'}, {'revid': 2478517786, 'parentid': 2467971484, 'user': 'Aca', 'timestamp': '2026-04-05T10:51:22Z', 'size': 166087, 'comment': '/* clientsitelink-update:0|shwiki|shwiki:Upad u Kapitol Sjedinjenih Država 6. januara 2021.|shwiki:Napad na Kapitol Sjedinjenih Američkih Država 6. januara */'}, {'revid': 2467971484, 'parentid': 2462828698, 'user': 'Andreas003', 'timestamp': '2026-02-28T12:48:14Z', 'size': 166080, 'comment': '/* wbsetsitelink-set:1|etwiki */ 2021. aasta rünnak Ameerika Ühendriikide Kapitooliumile'}, {'revid': 2462828698, 'parentid': 2462828694, 'user': 'Bluepolarbear247', 'timestamp': '2026-02-12T13:04:50Z', 'size': 166069, 'comment': '/* wbsetdescription-set:1|ko */ 2021년 1월 6일에 미국 국회의사당에서 대통령 선거인단 투표 집계를 저지하려는 목적으로 발생한 소요사태'}, {'revid': 2462828694, 'parentid': 2461780066, 'user': 'Bluepolarbear247', 'timestamp': '2026-02-12T13:04:49Z', 'size': 165991, 'comment': '/* wbsetlabel-set:1|ko */ 2021년 미국 국회의사당 습격'}, {'revid': 2461780066, 'parentid': 2461780048, 'user': 'Treisijs', 'timestamp': '2026-02-08T16:05:24Z', 'size': 165991, 'comment': '/* wbsetaliases-add:1|lv */ 6. janvāra uzbrukums ASV Kapitolijam'}, {'revid': 2461780048, 'parentid': 2461780047, 'user': 'Treisijs', 'timestamp': '2026-02-08T16:05:15Z', 'size': 165900, 'comment': '/* wbsetaliases-add:1|lv */ 2021. gada 6. janvāra uzbrukums ASV Kapitolijam'}, {'revid': 2461780047, 'parentid': 2460817388, 'user': 'Treisijs', 'timestamp': '2026-02-08T16:05:14Z', 'size': 165783, 'comment': '/* wbsetlabel-add:1|lv */ uzbrukums ASV Kapitolijam'}, {'revid': 2460817388, 'parentid': 2460816772, 'user': 'Peaceray', 'timestamp': '2026-02-05T06:35:04Z', 'size': 165699, 'comment': '/* wbsetclaim-update:2||1|1 */ [[Property:P5248]]: [[Q7507196]]'}, {'revid': 2460816772, 'parentid': 2460816710, 'user': 'Peaceray', 'timestamp': '2026-02-05T06:31:05Z', 'size': 164423, 'comment': '/* wbsetclaim-update:2||1|1 */ [[Property:P8032]]: [[Q117229488]]'}, {'revid': 2460816710, 'parentid': 2460816545, 'user': 'Peaceray', 'timestamp': '2026-02-05T06:30:54Z', 'size': 162016, 'comment': '/* wbsetclaim-update:2||1|1 */ [[Property:P8032]]: [[Q117229468]]'}, {'revid': 2460816545, 'parentid': 2460816178, 'user': 'Peaceray', 'timestamp': '2026-02-05T06:30:14Z', 'size': 159609, 'comment': '/* wbsetclaim-update:2||1|1 */ [[Property:P8032]]: [[Q117229435]]'}, {'revid': 2460816178, 'parentid': 2460815978, 'user': 'Peaceray', 'timestamp': '2026-02-05T06:28:21Z', 'size': 157202, 'comment': '/* wbsetclaim-update:2||1|1 */ [[Property:P8032]]: [[Q104709251]]'}, {'revid': 2460815978, 'parentid': 2460815008, 'user': 'Peaceray', 'timestamp': '2026-02-05T06:27:08Z', 'size': 155810, 'comment': '/* wbsetclaim-update:2||1|1 */ [[Property:P8032]]: [[Q104721808]]'}, {'revid': 2460815008, 'parentid': 2460814555, 'user': 'Peaceray', 'timestamp': '2026-02-05T06:22:08Z', 'size': 153622, 'comment': '/* wbsetclaim-update:2||1 */ [[Property:P8031]]: [[Q109405495]]'}, {'revid': 2460814555, 'parentid': 2460813981, 'user': 'Peaceray', 'timestamp': '2026-02-05T06:19:46Z', 'size': 151908, 'comment': '/* wbsetclaim-update:2||1|2 */ [[Property:P8031]]: [[Q7331704]]'}, {'revid': 2460813981, 'parentid': 2460813482, 'user': 'Peaceray', 'timestamp': '2026-02-05T06:16:03Z', 'size': 147737, 'comment': '/* wbsetclaim-update:2||1|1 */ [[Property:P8031]]: [[Q59268549]]'}, {'revid': 2460813482, 'parentid': 2460812690, 'user': 'Peaceray', 'timestamp': '2026-02-05T06:12:40Z', 'size': 146156, 'comment': '/* wbsetclaim-update:2||1|1 */ [[Property:P8031]]: [[Q104776680]]'}, {'revid': 2460812690, 'parentid': 2460812337, 'user': 'Peaceray', 'timestamp': '2026-02-05T06:08:53Z', 'size': 143783, 'comment': '/* wbsetclaim-update:2||1|1 */ [[Property:P8031]]: [[Q104742040]]'}, {'revid': 2460812337, 'parentid': 2460811695, 'user': 'Peaceray', 'timestamp': '2026-02-05T06:07:15Z', 'size': 141954, 'comment': '/* wbsetclaim-update:2||1|1 */ [[Property:P8031]]: [[Q104709251]]'}, {'revid': 2460811695, 'parentid': 2460809751, 'user': 'Peaceray', 'timestamp': '2026-02-05T06:02:50Z', 'size': 140562, 'comment': '/* wbsetclaim-update:2||1|1 */ [[Property:P8031]]: [[Q38271407]]'}, {'revid': 2460809751, 'parentid': 2460809386, 'user': 'Peaceray', 'timestamp': '2026-02-05T05:52:52Z', 'size': 138184, 'comment': '/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: 919'}, {'revid': 2460809386, 'parentid': 2460809098, 'user': 'Peaceray', 'timestamp': '2026-02-05T05:51:14Z', 'size': 137871, 'comment': '/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: 919'}, {'revid': 2460809098, 'parentid': 2460808630, 'user': 'Peaceray', 'timestamp': '2026-02-05T05:49:59Z', 'size': 136452, 'comment': '/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: 725'}, {'revid': 2460808630, 'parentid': 2460808517, 'user': 'Peaceray', 'timestamp': '2026-02-05T05:47:41Z', 'size': 135809, 'comment': '/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: 870'}, {'revid': 2460808517, 'parentid': 2460804346, 'user': 'Peaceray', 'timestamp': '2026-02-05T05:47:09Z', 'size': 135494, 'comment': '/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: 950'}, {'revid': 2460804346, 'parentid': 2460804179, 'user': 'Peaceray', 'timestamp': '2026-02-05T05:20:54Z', 'size': 134846, 'comment': '/* wbsetclaim-update:2||1|1 */ [[Property:P5582]]: no value'}, {'revid': 2460804179, 'parentid': 2460804112, 'user': 'Peaceray', 'timestamp': '2026-02-05T05:19:37Z', 'size': 134579, 'comment': '/* wbsetclaim-update:2||1 */ [[Property:P5582]]: no value'}, {'revid': 2460804112, 'parentid': 2460803754, 'user': 'Peaceray', 'timestamp': '2026-02-05T05:19:04Z', 'size': 134582, 'comment': '/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: no value'}, {'revid': 2460803754, 'parentid': 2452504397, 'user': 'Peaceray', 'timestamp': '2026-02-05T05:16:09Z', 'size': 133938, 'comment': '/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: 1,265'}, {'revid': 2452504397, 'parentid': 2452337340, 'user': 'AllanFerreira98', 'timestamp': '2026-01-07T18:30:45Z', 'size': 133292, 'comment': '/* wbsetdescription-set:1|pt */ tentativa de golpe de Estado de apoiadores de Donald Trump para impedir ou influenciar a contagem de votos eleitorais presidenciais'}, {'revid': 2452337340, 'parentid': 2452337066, 'user': 'Doug Grinbergs', 'timestamp': '2026-01-07T05:21:21Z', 'size': 133271, 'comment': '/* wbeditentity-update-languages-short:0||en */'}, {'revid': 2452337066, 'parentid': 2446565495, 'user': 'Doug Grinbergs', 'timestamp': '2026-01-07T05:20:16Z', 'size': 133201, 'comment': '/* wbeditentity-update-languages-short:0||en */'}, {'revid': 2446565495, 'parentid': 2446043480, 'user': 'DanGFSouza', 'timestamp': '2025-12-24T13:56:47Z', 'size': 133070, 'comment': '/* wbcreateclaim-create:1| */ [[Property:P11924]]: 2021-u.s.-capitol-insurrection'}, {'revid': 2446043480, 'parentid': 2439644108, 'user': 'Totorvdr59', 'timestamp': '2025-12-23T13:02:40Z', 'size': 132695, 'comment': '/* wbsetaliases-add:1|fr */ assaut du Capitole'}, {'revid': 2439644108, 'parentid': 2436061974, 'user': 'MatSuBot', 'timestamp': '2025-12-08T16:14:02Z', 'size': 132623, 'comment': '/* wbeditentity-update-languages-short:0||tok */ import labels from sitelinks'}, {'revid': 2436061974, 'parentid': 2432757851, 'user': '.hecko', 'timestamp': '2025-11-30T14:09:02Z', 'size': 132505, 'comment': '/* wbsetsitelink-add:1|tokwiki */ jan li utala e tomo lawa pi ma Mewika lon tenpo sike 2021'}, {'revid': 2432757851, 'parentid': 2429587197, 'user': 'Doug Grinbergs', 'timestamp': '2025-11-23T05:14:49Z', 'size': 132364, 'comment': '/* wbeditentity-update-languages-short:0||en */'}, {'revid': 2429587197, 'parentid': 2422009559, 'user': 'UndefinedRachel', 'timestamp': '2025-11-14T17:08:59Z', 'size': 132221, 'comment': '/* wbcreateclaim-create:1| */ [[Property:P3106]]: us-news/us-capitol-breach, [[:toollabs:quickstatements/#/batch/251965|batch #251965]]'}, {'revid': 2422009559, 'parentid': 2422009539, 'user': 'BorkedBot', 'timestamp': '2025-10-26T02:09:43Z', 'size': 131853, 'comment': '/* wbremoveclaims-remove:1| */ [[Property:P6760]]: 36218, removing old kym id ([[:toolforge:editgroups/b/CB/56d4d76c489a|details]])'}, {'revid': 2422009539, 'parentid': 2422009521, 'user': 'BorkedBot', 'timestamp': '2025-10-26T02:09:40Z', 'size': 132200, 'comment': '/* wbsetreference-add:2| */ [[Property:P13484]]: january-6th-2021-storming-of-the-united-states-capitol, migrate kym ([[:toolforge:editgroups/b/CB/56d4d76c489a|details]]) (adding sources)'}, {'revid': 2422009521, 'parentid': 2410836419, 'user': 'BorkedBot', 'timestamp': '2025-10-26T02:09:37Z', 'size': 131355, 'comment': '/* wbsetclaim-create:2||1 */ [[Property:P13484]]: january-6th-2021-storming-of-the-united-states-capitol, migrate kym ([[:toolforge:editgroups/b/CB/56d4d76c489a|details]])'}, {'revid': 2410836419, 'parentid': 2410836274, 'user': 'Chrz', 'timestamp': '2025-09-29T21:11:50Z', 'size': 129396, 'comment': '/* wbsetlabel-set:1|cs */ útok na Kapitol Spojených států amerických (2021)'}, {'revid': 2410836274, 'parentid': 2406033421, 'user': 'Chrz', 'timestamp': '2025-09-29T21:11:19Z', 'size': 129394, 'comment': '/* clientsitelink-update:0|cswiki|cswiki:Útok na Kapitol Spojených států amerických 2021|cswiki:Útok na Kapitol Spojených států amerických (2021) */'}, {'revid': 2406033421, 'parentid': 2406027101, 'user': 'Girligaanshub', 'timestamp': '2025-09-16T16:02:06Z', 'size': 129392, 'comment': '/* wbsetclaim-create:2||1 */ [[Property:P3342]]: [[Q99826651]]'}, {'revid': 2406027101, 'parentid': 2400408504, 'user': 'Girligaanshub', 'timestamp': '2025-09-16T15:43:49Z', 'size': 128973, 'comment': '/* wbsetclaim-create:2||1 */ [[Property:P664]]: [[Q99826651]]'}, {'revid': 2400408504, 'parentid': 2400338787, 'user': 'SimplyFreddie', 'timestamp': '2025-09-04T15:24:49Z', 'size': 128555, 'comment': '/* wbsetsitelink-set:1|srwiki */ Јуриш на Капитол Сједињених Америчких Држава 2021.'}, {'revid': 2400338787, 'parentid': 2382727173, 'user': '87.116.165.111', 'anon': '', 'timestamp': '2025-09-04T12:44:51Z', 'size': 128565, 'comment': '/* wbsetsitelink-set:1|srwiki */ Протести код Капитола Сједињених Америчких Држава 2021.'}, {'revid': 2382727173, 'parentid': 2382727170, 'user': 'Lxlalexlxl', 'timestamp': '2025-07-22T11:20:13Z', 'size': 128555, 'comment': '/* wbsetaliases-update:2|uk */ штурм будівлі Капітолія прихильниками Дональда Трампа, штурм будівлі Капітолія'}, {'revid': 2382727170, 'parentid': 2382396466, 'user': 'Lxlalexlxl', 'timestamp': '2025-07-22T11:20:12Z', 'size': 128555, 'comment': '/* wbsetlabel-set:1|uk */ Протести в США біля Капітолія 6 січня 2021'}, {'revid': 2382396466, 'parentid': 2379185854, 'user': 'MatSuBot', 'timestamp': '2025-07-21T13:52:10Z', 'size': 128555, 'comment': '/* wbeditentity-update-languages-short:0||kk */ import labels from sitelinks'}, {'revid': 2379185854, 'parentid': 2376107564, 'user': 'TheNomadEditor', 'timestamp': '2025-07-13T18:31:58Z', 'size': 128445, 'comment': '/* wbsetsitelink-add:1|kkwiki */ АҚШ Капитолийіне шабуыл (2021)'}, {'revid': 2376107564, 'parentid': 2360605238, 'user': 'YaleLuxBot', 'timestamp': '2025-07-08T18:20:50Z', 'size': 128312, 'comment': '/* wbcreateclaim-create:1| */ [[Property:P13591]]: activity/43b26d4a-3460-4ed8-9640-4c5384fda49c'}, {'revid': 2360605238, 'parentid': 2359102854, 'user': 'Dotruonggiahy12', 'timestamp': '2025-06-14T01:29:54Z', 'size': 127922, 'comment': '/* wbsetdescription-set:1|vi */ vụ tấn công nhằm ngăn việc chứng nhận bầu cử tổng thống Hoa Kỳ vào ngày 6 tháng 1 năm 2021'}, {'revid': 2359102854, 'parentid': 2352397391, 'user': 'Danyele', 'timestamp': '2025-06-10T18:50:14Z', 'size': 127923, 'comment': "/* wbsetlabel-set:1|it */ assalto al Campidoglio degli Stati Uniti d'America del 2021"}, {'revid': 2352397391, 'parentid': 2348483050, 'user': 'Trade', 'timestamp': '2025-05-25T19:32:51Z', 'size': 127923, 'comment': '/* wbcreateclaim-create:1| */ [[Property:P13300]]: capitol-hill-attack'}, {'revid': 2348483050, 'parentid': 2304032097, 'user': 'MsynBot', 'timestamp': '2025-05-14T12:19:24Z', 'size': 127559, 'comment': '/* wbeditentity-update:0| */ remove unnecessary use of preferred rank #msynbotTask13'}, {'revid': 2304032097, 'parentid': 2300854996, 'user': '118.235.4.44', 'anon': '', 'timestamp': '2025-01-30T04:34:53Z', 'size': 127565, 'comment': '/* wbsetclaim-create:2||1 */ [[Property:P8885]]: 2021년 미국 국회의사당 점거 폭동'}, {'revid': 2300854996, 'parentid': 2300451325, 'user': 'Kooma', 'timestamp': '2025-01-21T17:23:39Z', 'size': 127178, 'comment': '/* restore:0||2287927996|Pyb en résidence */'}, {'revid': 2300451325, 'parentid': 2291305687, 'user': '2A01:9700:9130:3700:C474:5DE3:3B1B:44EC', 'anon': '', 'timestamp': '2025-01-20T18:38:23Z', 'size': 126344, 'comment': '/* wbsetclaim-update:2||1 */ [[Property:P1120]]: 5,000'}, {'revid': 2291305687, 'parentid': 2287927996, 'user': '2603:7080:29F0:8ED0:E90F:FAA5:1AED:4BA5', 'anon': '', 'timestamp': '2024-12-25T18:27:28Z', 'size': 126341, 'comment': '/* wbsetclaim-update:2||1|2 */ [[Property:P31]]: [[Q25906438]]'}, {'revid': 2287927996, 'parentid': 2286570416, 'user': 'Pyb en résidence', 'timestamp': '2024-12-15T23:12:16Z', 'size': 127178, 'comment': '/* wbsetclaim-create:2||1 */ [[Property:P9346]]: assaut-du-capitole, +ID France 24 FR ([[:toollabs:editgroups/b/OR/f2bf27d1403|details]])'}, {'revid': 2286570416, 'parentid': 2276196421, 'user': 'Jock64', 'timestamp': '2024-12-13T00:26:18Z', 'size': 126817, 'comment': '/* wbsetdescription-set:1|en-us */ 2021 mob attempt to prevent or influence the presidential electoral vote count'}, {'revid': 2276196421, 'parentid': 2261588118, 'user': 'MHGM357', 'timestamp': '2024-11-17T19:44:32Z', 'size': 126813, 'comment': '/* clientsitelink-update:0|fawiki|fawiki:یورش ۲۰۲۱ به کاخ کنگره ایالات متحده|fawiki:حمله ۶ ژانویه به ساختمان کنگره ایالات متحده آمریکا */'}, {'revid': 2261588118, 'parentid': 2261579096, 'user': 'Rhododendrites', 'timestamp': '2024-10-17T00:44:37Z', 'size': 126785, 'comment': '/* clientsitelink-update:0|enwiki|enwiki:January 6 United States Coup attempt by President Donald Trump|enwiki:January 6 United States Capitol attack */'}, {'revid': 2261579096, 'parentid': 2260651174, 'user': 'Qwerty786', 'timestamp': '2024-10-16T23:39:11Z', 'size': 126809, 'comment': '/* clientsitelink-update:0|enwiki|enwiki:January 6 United States Capitol attack|enwiki:January 6 United States Coup attempt by President Donald Trump */'}, {'revid': 2260651174, 'parentid': 2257197779, 'user': 'Tuhin', 'timestamp': '2024-10-14T18:18:38Z', 'size': 126785, 'comment': '/* clientsitelink-update:0|bnwiki|bnwiki:৬ জানুয়ারি,২০২১-এ যুক্তরাষ্ট্রের কংগ্রেসে হামলা|bnwiki:২০২১ যুক্তরাষ্ট্রের ক্যাপিটলে হামলা */'}, {'revid': 2257197779, 'parentid': 2256979814, 'minor': '', 'user': 'Wd-Ryan', 'timestamp': '2024-10-07T00:11:11Z', 'size': 126819, 'comment': 'Reverted edits by [[Special:Contributions/63.155.14.193|63.155.14.193]] ([[User talk:63.155.14.193|talk]]) to last revision by [[:User:AramBot|AramBot]]'}, {'revid': 2256979814, 'parentid': 2256977214, 'user': '63.155.14.193', 'anon': '', 'timestamp': '2024-10-06T09:59:13Z', 'size': 126828, 'comment': '/* wbsetlabel-set:1|en */ January 6 United States Capitol attack/NRK'}, {'revid': 2256977214, 'parentid': 2256976913, 'user': '63.155.14.193', 'anon': '', 'timestamp': '2024-10-06T09:49:01Z', 'size': 126824, 'comment': '/* wbsetclaim-update:2||1 */ [[Property:P5582]]: 1,999'}, {'revid': 2256976913, 'parentid': 2256976699, 'user': '63.155.14.193', 'anon': '', 'timestamp': '2024-10-06T09:47:44Z', 'size': 126824, 'comment': '/* wbsetclaim-update:2||1 */ [[Property:P5582]]: 9,999'}, {'revid': 2256976699, 'parentid': 2256976497, 'user': '63.155.14.193', 'anon': '', 'timestamp': '2024-10-06T09:46:49Z', 'size': 126823, 'comment': '/* wbsetclaim-update:2||1 */ [[Property:P8687]]: 24,900'}, {'revid': 2256976497, 'parentid': 2256976130, 'user': '63.155.14.193', 'anon': '', 'timestamp': '2024-10-06T09:45:57Z', 'size': 126823, 'comment': '/* wbsetclaim-update:2||1 */ [[Property:P1889]]: [[Q7889599]]'}, {'revid': 2256976130, 'parentid': 2241416994, 'user': '63.155.14.193', 'anon': '', 'timestamp': '2024-10-06T09:44:31Z', 'size': 126823, 'comment': '/* wbsetclaim-update:2||1 */ [[Property:P373]]: 2021 storming of the United States Capitol/NRK'}, {'revid': 2241416994, 'parentid': 2240237738, 'user': 'AramBot', 'timestamp': '2024-09-01T10:08:50Z', 'size': 126819, 'comment': '/* wbeditentity-update-languages-short:0||ckb */ Updating label from "هێرشکردنە سەر کۆنگرێسی ئەمریکا لەلایەن لایەنگرانی دۆناڵد ترامپ ٢٠٢١" to "ھێرشکردنە سەر کۆنگرێسی ئەمریکا لەلایەن لایەنگرانی دۆناڵد ترامپ"'}, {'revid': 2240237738, 'parentid': 2240223921, 'minor': '', 'user': 'Matěj Suchánek', 'timestamp': '2024-08-30T20:39:36Z', 'size': 126828, 'comment': 'Reverted edits by [[Special:Contributions/96.38.250.122|96.38.250.122]] ([[User talk:96.38.250.122|talk]]) to last revision by [[:User:Jason2016426|Jason2016426]]'}, {'revid': 2240223921, 'parentid': 2240223725, 'user': '96.38.250.122', 'anon': '', 'timestamp': '2024-08-30T20:14:24Z', 'size': 125611, 'comment': '/* wbremoveclaims-remove:1| */ [[Property:P8309]]: 18-321574'}, {'revid': 2240223725, 'parentid': 2236446160, 'user': '96.38.250.122', 'anon': '', 'timestamp': '2024-08-30T20:14:08Z', 'size': 126481, 'comment': '/* wbremoveclaims-remove:1| */ [[Property:P6760]]: 36218'}, {'revid': 2236446160, 'parentid': 2223850833, 'user': 'Jason2016426', 'timestamp': '2024-08-26T09:01:02Z', 'size': 126828, 'comment': '/* clientsitelink-update:0|wuuwiki|wuuwiki:1月6號國會山襲擊事幹|wuuwiki:国会山骚乱 */'}, {'revid': 2223850833, 'parentid': 2220737975, 'user': 'Ham II', 'timestamp': '2024-08-09T15:13:34Z', 'size': 126842, 'comment': '/* wbsetdescription-set:1|en */ 2021 attempt to prevent the U.S. presidential electoral vote count'}, {'revid': 2220737975, 'parentid': 2220737545, 'user': 'Ham II', 'timestamp': '2024-08-04T14:23:13Z', 'size': 126833, 'comment': '/* wbsetdescription-set:1|en */ 2021 attempt to prevent presidential electoral vote count'}, {'revid': 2220737545, 'parentid': 2219214301, 'user': 'Ham II', 'tim

In [3]:
print(len(revisions))
df = pd.DataFrame(revisions)
df.head()

1018

,revid,parentid,user,timestamp,size,comment,anon,minor,commenthidden,userhidden,suppressed
0,2504691802,2503966829,Vicarage,2026-06-11T17:20:01Z,167005,/* wbremoveclaims-remove:1| */ [[Property:P625...,NaN,NaN,NaN,NaN,NaN
1,2503966829,2503943744,Vicarage,2026-06-09T21:04:25Z,167520,/* undo:0||2503647430|Quesotiotyo */ Events cl...,NaN,NaN,NaN,NaN,NaN
2,2503943744,2503647430,Pi bot,2026-06-09T20:04:46Z,167005,/* wbsetclaim-create:2||1 */ [[Property:P625]]...,NaN,NaN,NaN,NaN,NaN
3,2503647430,2500170824,Quesotiotyo,2026-06-09T06:11:24Z,166474,/* wbremoveclaims-remove:1| */ [[Property:P625...,NaN,NaN,NaN,NaN,NaN
4,2500170824,2499912567,Twofivesixbot,2026-05-31T15:55:23Z,167006,/* wbsetclaim-update-qualifiers:1||1|2 */ [[Pr...,NaN,NaN,NaN,NaN,NaN

In [4]:
#see comments to figure out a way to exclude non-en language updates
for index, row in df.iterrows():
    print(row["comment"])

/* wbremoveclaims-remove:1| */ [[Property:P625]]: 38°53'23"N, 77°0'33"W, QuickStatements 3.0 [[:toollabs:qs-dev/batch/35934|batch #35934]]
/* undo:0||2503647430|Quesotiotyo */ Events clearly can have co-ordinates, removing them breaks lots of Wikipedia templates. User refused to engage even when asked repeatedly on talk ([[:toollabs:editgroups/b/EG/9c82e31|details]])
/* wbsetclaim-create:2||1 */ [[Property:P625]]: 38°53'23"N, 77°0'33"W, Importing coordinate from enwp
/* wbremoveclaims-remove:1| */ [[Property:P625]]: 38°53'23"N, 77°0'33"W, #quickstatements; #temporary_batch_1780981630519; property is not to be used on events (these belong to the location (P276) instead)
/* wbsetclaim-update-qualifiers:1||1|2 */ [[Property:P8189]]: 987011253755805171, mv to monolingual text names on J9U statements
/* wbsetdescription-set:1|de */ gewaltsamer Angriff auf das Kapitol durch Anhänger Donald Trumps am 6. Januar 2021
/* wbsetqualifier-add:1| */ [[Property:P9675]]: 131190, Add qualifier to WikiKids ID `Bestorming_van_het_Amerikaanse_Capitool_in_2021`
/* clientsitelink-update:0|shwiki|shwiki:Upad u Kapitol Sjedinjenih Država 6. januara 2021.|shwiki:Napad na Kapitol Sjedinjenih Američkih Država 6. januara */
/* wbsetsitelink-set:1|etwiki */ 2021. aasta rünnak Ameerika Ühendriikide Kapitooliumile
/* wbsetdescription-set:1|ko */ 2021년 1월 6일에 미국 국회의사당에서 대통령 선거인단 투표 집계를 저지하려는 목적으로 발생한 소요사태
/* wbsetlabel-set:1|ko */ 2021년 미국 국회의사당 습격
/* wbsetaliases-add:1|lv */ 6. janvāra uzbrukums ASV Kapitolijam
/* wbsetaliases-add:1|lv */ 2021. gada 6. janvāra uzbrukums ASV Kapitolijam
/* wbsetlabel-add:1|lv */ uzbrukums ASV Kapitolijam
/* wbsetclaim-update:2||1|1 */ [[Property:P5248]]: [[Q7507196]]
/* wbsetclaim-update:2||1|1 */ [[Property:P8032]]: [[Q117229488]]
/* wbsetclaim-update:2||1|1 */ [[Property:P8032]]: [[Q117229468]]
/* wbsetclaim-update:2||1|1 */ [[Property:P8032]]: [[Q117229435]]
/* wbsetclaim-update:2||1|1 */ [[Property:P8032]]: [[Q104709251]]
/* wbsetclaim-update:2||1|1 */ [[Property:P8032]]: [[Q104721808]]
/* wbsetclaim-update:2||1 */ [[Property:P8031]]: [[Q109405495]]
/* wbsetclaim-update:2||1|2 */ [[Property:P8031]]: [[Q7331704]]
/* wbsetclaim-update:2||1|1 */ [[Property:P8031]]: [[Q59268549]]
/* wbsetclaim-update:2||1|1 */ [[Property:P8031]]: [[Q104776680]]
/* wbsetclaim-update:2||1|1 */ [[Property:P8031]]: [[Q104742040]]
/* wbsetclaim-update:2||1|1 */ [[Property:P8031]]: [[Q104709251]]
/* wbsetclaim-update:2||1|1 */ [[Property:P8031]]: [[Q38271407]]
/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: 919
/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: 919
/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: 725
/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: 870
/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: 950
/* wbsetclaim-update:2||1|1 */ [[Property:P5582]]: no value
/* wbsetclaim-update:2||1 */ [[Property:P5582]]: no value
/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: no value
/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: 1,265
/* wbsetdescription-set:1|pt */ tentativa de golpe de Estado de apoiadores de Donald Trump para impedir ou influenciar a contagem de votos eleitorais presidenciais
/* wbeditentity-update-languages-short:0||en */
/* wbeditentity-update-languages-short:0||en */
/* wbcreateclaim-create:1| */ [[Property:P11924]]: 2021-u.s.-capitol-insurrection
/* wbsetaliases-add:1|fr */ assaut du Capitole
/* wbeditentity-update-languages-short:0||tok */ import labels from sitelinks
/* wbsetsitelink-add:1|tokwiki */ jan li utala e tomo lawa pi ma Mewika lon tenpo sike 2021
/* wbeditentity-update-languages-short:0||en */
/* wbcreateclaim-create:1| */ [[Property:P3106]]: us-news/us-capitol-breach, [[:toollabs:quickstatements/#/batch/251965|batch #251965]]
/* wbremoveclaims-remove:1| */ [[Property:P6760]]: 36218, removing old kym id ([[:toolforge:editgroups/b/CB/56d4d76c489a|details]])
/* wbsetreference-add:2| */ [[Property:P13484]]: january-6th-2021-storming-of-the-united-states-capitol, migrate kym ([[:toolforge:editgroups/b/CB/56d4d76c489a|details]]) (adding sources)
/* wbsetclaim-create:2||1 */ [[Property:P13484]]: january-6th-2021-storming-of-the-united-states-capitol, migrate kym ([[:toolforge:editgroups/b/CB/56d4d76c489a|details]])
/* wbsetlabel-set:1|cs */ útok na Kapitol Spojených států amerických (2021)
/* clientsitelink-update:0|cswiki|cswiki:Útok na Kapitol Spojených států amerických 2021|cswiki:Útok na Kapitol Spojených států amerických (2021) */
/* wbsetclaim-create:2||1 */ [[Property:P3342]]: [[Q99826651]]
/* wbsetclaim-create:2||1 */ [[Property:P664]]: [[Q99826651]]
/* wbsetsitelink-set:1|srwiki */ Јуриш на Капитол Сједињених Америчких Држава 2021.
/* wbsetsitelink-set:1|srwiki */ Протести код Капитола Сједињених Америчких Држава 2021.
/* wbsetaliases-update:2|uk */ штурм будівлі Капітолія прихильниками Дональда Трампа, штурм будівлі Капітолія
/* wbsetlabel-set:1|uk */ Протести в США біля Капітолія 6 січня 2021
/* wbeditentity-update-languages-short:0||kk */ import labels from sitelinks
/* wbsetsitelink-add:1|kkwiki */ АҚШ Капитолийіне шабуыл (2021)
/* wbcreateclaim-create:1| */ [[Property:P13591]]: activity/43b26d4a-3460-4ed8-9640-4c5384fda49c
/* wbsetdescription-set:1|vi */ vụ tấn công nhằm ngăn việc chứng nhận bầu cử tổng thống Hoa Kỳ vào ngày 6 tháng 1 năm 2021
/* wbsetlabel-set:1|it */ assalto al Campidoglio degli Stati Uniti d'America del 2021
/* wbcreateclaim-create:1| */ [[Property:P13300]]: capitol-hill-attack
/* wbeditentity-update:0| */ remove unnecessary use of preferred rank #msynbotTask13
/* wbsetclaim-create:2||1 */ [[Property:P8885]]: 2021년 미국 국회의사당 점거 폭동
/* restore:0||2287927996|Pyb en résidence */
/* wbsetclaim-update:2||1 */ [[Property:P1120]]: 5,000
/* wbsetclaim-update:2||1|2 */ [[Property:P31]]: [[Q25906438]]
/* wbsetclaim-create:2||1 */ [[Property:P9346]]: assaut-du-capitole, +ID France 24 FR ([[:toollabs:editgroups/b/OR/f2bf27d1403|details]])
/* wbsetdescription-set:1|en-us */ 2021 mob attempt to prevent or influence the presidential electoral vote count
/* clientsitelink-update:0|fawiki|fawiki:یورش ۲۰۲۱ به کاخ کنگره ایالات متحده|fawiki:حمله ۶ ژانویه به ساختمان کنگره ایالات متحده آمریکا */
/* clientsitelink-update:0|enwiki|enwiki:January 6 United States Coup attempt by President Donald Trump|enwiki:January 6 United States Capitol attack */
/* clientsitelink-update:0|enwiki|enwiki:January 6 United States Capitol attack|enwiki:January 6 United States Coup attempt by President Donald Trump */
/* clientsitelink-update:0|bnwiki|bnwiki:৬ জানুয়ারি,২০২১-এ যুক্তরাষ্ট্রের কংগ্রেসে হামলা|bnwiki:২০২১ যুক্তরাষ্ট্রের ক্যাপিটলে হামলা */
Reverted edits by [[Special:Contributions/63.155.14.193|63.155.14.193]] ([[User talk:63.155.14.193|talk]]) to last revision by [[:User:AramBot|AramBot]]
/* wbsetlabel-set:1|en */ January 6 United States Capitol attack/NRK
/* wbsetclaim-update:2||1 */ [[Property:P5582]]: 1,999
/* wbsetclaim-update:2||1 */ [[Property:P5582]]: 9,999
/* wbsetclaim-update:2||1 */ [[Property:P8687]]: 24,900
/* wbsetclaim-update:2||1 */ [[Property:P1889]]: [[Q7889599]]
/* wbsetclaim-update:2||1 */ [[Property:P373]]: 2021 storming of the United States Capitol/NRK
/* wbeditentity-update-languages-short:0||ckb */ Updating label from "هێرشکردنە سەر کۆنگرێسی ئەمریکا لەلایەن لایەنگرانی دۆناڵد ترامپ ٢٠٢١" to "ھێرشکردنە سەر کۆنگرێسی ئەمریکا لەلایەن لایەنگرانی دۆناڵد ترامپ"
Reverted edits by [[Special:Contributions/96.38.250.122|96.38.250.122]] ([[User talk:96.38.250.122|talk]]) to last revision by [[:User:Jason2016426|Jason2016426]]
/* wbremoveclaims-remove:1| */ [[Property:P8309]]: 18-321574
/* wbremoveclaims-remove:1| */ [[Property:P6760]]: 36218
/* clientsitelink-update:0|wuuwiki|wuuwiki:1月6號國會山襲擊事幹|wuuwiki:国会山骚乱 */
/* wbsetdescription-set:1|en */ 2021 attempt to prevent the U.S. presidential electoral vote count
/* wbsetdescription-set:1|en */ 2021 attempt to prevent presidential electoral vote count
/* wbsetlabeldescriptionaliases:3|en */ January 6 United States Capitol attack, 2021 mob attempt to prevent Presidential electoral vote count, January 2021 United States Capitol protests, storming of the Capitol Building by Donald Trump's supporters, Capitol Building storming, 2021 United States Capitol protests, January 2021 insurrection, Insurrection of the US Capitol, 2021 U.S. Capitol riot, 2021 United States Capitol attack, Storming of the Capitol, Jan 6 storming of the United States Cap...
Reverted edits by [[Special:Contributions/186.91.198.179|186.91.198.179]] ([[User talk:186.91.198.179|talk]]) to last revision by [[:User:MatSuBot|MatSuBot]]
/* wbsetclaim-update:2||1 */ [[Property:P580]]: 2021
/* wbsetclaim-create:2||1 */ [[Property:P582]]: 2021
/* wbsetclaim-create:2||1 */ [[Property:P580]]: 202
/* wbeditentity-update-languages-short:0||wuu */ add missing labels
/* clientsitelink-update:0|zh_yuewiki|zh_yuewiki:美國國會大廈衝突|zh_yuewiki:美國國會大廈暴動 */
/* wbeditentity-update-languages-short:0||hr */
/* wblinktitles-connect:2| */ enwiki:January 6 United States Capitol attack, wuuwiki:1月6號國會山襲擊事幹
Reverted edits by [[Special:Contributions/2601:644:907E:A450:A5E1:78E5:F367:2700|2601:644:907E:A450:A5E1:78E5:F367:2700]] ([[User talk:2601:644:907E:A450:A5E1:78E5:F367:2700|talk]]) to last revision by [[:User:Matěj Suchánek|Matěj Suchánek]]
/* wbsetclaim-create:2||1 */ [[Property:P31]]: [[Q124757]]
Reverted edits by [[Special:Contributions/บดินทร์ อินทะปัญโญ|บดินทร์ อินทะปัญโญ]] ([[User talk:บดินทร์ อินทะปัญโญ|talk]]) to last revision by [[:User:Bigmorr|Bigmorr]]
/* wbsetdescription-add:1|th */ ความสมดุลโลก, #suggestededit-add-desc 1.0
/* wbsetaliases-add:2|zh */ 國會山莊騷亂案, 國會山莊暴動案
/* wbsetaliases-add:4|zh */ 国会山骚乱, 國會山騷亂, 國會山莊騷亂事件, 國會山莊暴動事件
/* wbeditentity-update-languages-short:0||si */ add missing labels
/* wbsetsitelink-add:1|commonswiki */ 2021 storming of the United States Capitol
/* wbsetsitelink-add:1|siwiki */ ජනවාරි 6 එක්සත් ජනපදයේ කැපිටල් ප්‍රහාරය
Reverted edits by [[Special:Contributions/50.48.225.223|50.48.225.223]] ([[User talk:50.48.225.223|talk]]) to last revision by [[:User:Roshkara|Roshkara]]
/* wbremoveclaims-remove:1| */ [[Property:P18]]: 2021 storming of the United States Capitol 09.jpg
/* wbremoveclaims-remove:1| */ [[Property:P31]]: no value
/* wbremoveclaims-remove:1| */ [[Property:P973]]: https://www.propublica.org/article/capitol-rioters-planned-for-weeks-in-plain-sight-the-police-werent-ready
/* wbsetclaim-update:2||1|4 */ [[Property:P973]]: https://www.propublica.org/article/capitol-rioters-planned-for-weeks-in-plain-sight-the-police-werent-ready
/* wbsetclaim-update:2||1|2 */ [[Property:P1339]]: 50
/* wbsetclaim-update:2||1|2 */ [[Property:P1339]]: 50
/* wbsetclaim-update:2||1|2 */ [[Property:P664]]: [[Q29096457]]
/* wbremoveclaims-remove:1| */ [[Property:P2348]]: [[Q27809653]]
/* wbremoveclaims-remove:1| */ [[Property:P155]]: [[Q104717056]]
/* wbremoveclaims-remove:1| */ [[Property:P276]]: [[Q54109]]
/* wbremoveclaims-remove:1| */ [[Property:P17]]: [[Q30]]
/* wbremoveclaims-remove:1| */ [[Property:P10]]: US Congress Breached by Protesters (Source).webm
/* wbremoveclaims-remove:1| */ [[Property:P1269]]: [[Q27809653]]
/* wbremoveclaims-remove:1| */ [[Property:P31]]: no value
/* wbremoveclaims-remove:1| */ [[Property:P31]]: no value
/* wbremoveclaims-remove:1| */ [[Property:P31]]: [[Q124734]]
/* wbremoveclaims-remove:1| */ [[Property:P31]]: [[Q30314106]]
/* wbsetclaim-update:2||1 */ [[Property:P31]]: no value
/* wbsetclaim-update:2||1 */ [[Property:P31]]: no value
/* wbsetclaim-update:2||1 */ [[Property:P31]]: no value
/* wbsetclaim-update:2||1 */ [[Property:P31]]: no value
/* wbsetclaim-update:2||1 */ [[Property:P31]]: [[Q25906438]]
/* restore:0||2068470705|SR5 */ rvv
/* wbsetaliases-update:21|en */ January 2021 United States Capitol protests, storming of the Capitol Building by Donald Trump's supporters, Capitol Building storming, 2021 United States Capitol protests, January 2021 insurrection, Insurrection of the US Capitol, 2021 U.S. Capitol riot, 2021 United States Capitol attack, Storming of the Capitol, Jan 6 storming of the United States Capitol, January 6 storming of the United States Capitol, 1/6/2021, 1/6/21, Capitol Insurrection, January six insu...
/* wbsetdescription-remove:1|en */ 2021 mob attempt to prevent Presidential electoral vote count
/* wbsetlabel-remove:1|en */ 2021 storming of the United States Capitol
/* wbsetlabel-set:1|ar */ اقتحام كابيتول الولايات المتحدة 2021, [[:toollabs:quickstatements/#/batch/223343|batch #223343]]
/* wbsetaliases-add:1|fi */ loppiaiskapina
/* wbeditentity-update-languages-short:0||ki */ add missing labels
/* wbeditentity-update-languages-short:0||nb */
/* wbeditentity-update-languages-short:0||nb */
/* clientsitelink-update:0|zhwiki|zhwiki:2021年美国国会大厦袭击事件|zhwiki:国会山骚乱 */
/* wbsetdescription-set:1|ru */ попытка демонстрантов в 2021 году предотвратить смену власти в США по итогам выборов 2020 года
/* wbsetlabel-set:1|ru */ захват Капитолия
/* wbsetclaim-update:2||1 */ [[Property:P5582]]: 1,265
/* wbsetclaim-update:2||1 */ [[Property:P5582]]: no value
/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: 1,265
/* wbsetclaim-create:2||1 */ [[Property:P5582]]: 1,265
/* wblinktitles-connect:2| */ enwiki:January 6 United States Capitol attack, kiwiki:January 6, Itharĩkĩra rĩa Capitol (Amerika)
/* wbsetdescription-add:1|gv */ riftanyn elgyssagh ren soiagh er Ard-whaiyl ny Steatyn Unnaneysit noi eiyrtyssyn y reihys eaghtyraneagh
/* wbsetlabel-add:1|gv */ soiagh er Ard-whaiyl ny Steatyn Unnaneysit
/* wbsetsitelink-add:1|gvwiki */ Soiagh er Ard-whaiyl ny Steatyn Unnaneysit, 2021
/* wbcreateclaim-create:1| */ [[Property:P12086]]: Bestorming_van_het_Amerikaanse_Capitool_in_2021, [[:toollabs:quickstatements/#/batch/220142|batch #220142]]
Reverted edits by [[Special:Contributions/108.174.97.59|108.174.97.59]] ([[User talk:108.174.97.59|talk]]) to last revision by [[:User:Johshh|Johshh]]
/* wbsetdescription-set:1|en */ efforts to stop the certification of Electoral count vote to certify the results of the 2020 U.S. presidential election
/* wbsetclaim-update:2||1 */ [[Property:P5582]]: 1,106
/* wbsetclaim-update:2||1 */ [[Property:P5582]]: 950
/* wbsetclaim-update:2||1|2 */ [[Property:P3984]]: January6
/* wbsetclaim-update:2||1|2 */ [[Property:P3984]]: January6
/* clientsitelink-update:0|hywiki|hywiki:ԱՄՆ Կապիտոլիումի գրոհում (2021)|hywiki:ԱՄՆ Կապիտոլիումի վրա հարձակում (2021) */
/* wbsetqualifier-add:1| */ [[Property:P2093]]: Brian Duignan, [[:toollabs:quickstatements/#/batch/214120|batch #214120]]
/* wbsetqualifier-add:1| */ [[Property:P1810]]: January 6 U.S. Capitol attack, [[:toollabs:quickstatements/#/batch/214120|batch #214120]]
/* wbsetlabel-set:1|sl */ napad na Kapitol Združenih držav Amerike leta 2021
/* wbsetaliases-update:1|sl */ napad na Kapitol
/* wbsetaliases-add:1|sl */ napad na Kaptol
/* wbsetlabel-set:1|sl */ napad na kapitol Združenih držav Amerike leta 2021
/* wbsetclaim-create:2||1 */ [[Property:P5582]]: 1,106
/* wbsetlabel-set:1|hu */ az Amerikai Egyesült Államok Capitoliumának ostroma
/* undo:0||1937315141|45.132.115.75 */
/* wbsetlabel-set:1|en */ LIES
/* wbsetdescription-add:1|ang */ 2021 folcweallunga tōforhtian preostlice cyneþrymmes weorþscipe rǣd gerihtan
/* wbsetlabel-add:1|ang */ þunorung 2021 oferstigende ðære Unitegan Statum Capitole
/* wbsetdescription-set:1|en */ 2021 mob attempt to prevent Presidential electoral vote count, ([[w:en:Wikipedia:Shortdesc helper|Shortdesc helper]])
/* wbsetreference-add:2| */ [[Property:P1617]]: 803447c0-7eaa-4f9b-9b6b-db7ad58034b8, #quickstatements; #temporary_batch_1686858916515
/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: 870
/* wbsetclaim-update:2||1|2 */ [[Property:P5582]]: 999
/* clientsitelink-update:0|simplewiki|simplewiki:2021 United States Capitol attack|simplewiki:January 6 United States Capitol attack */
/* wbsetclaim-create:2||1 */ [[Property:P8687]]: 161,676, add reddit sub count
/* wbsetqualifier-add:1| */ [[Property:P585]]: 23 May 2023, update subreddit data
/* wbsetqualifier-add:1| */ [[Property:P407]]: [[Q1860]], update subreddit data
/* wbsetqualifier-add:1| */ [[Property:P580]]: 9 January 2021, update subreddit data
/* wbsetqualifier-add:1| */ [[Property:P1810]]: CapitolConsequences, update subreddit data
/* wbsetclaim-create:2||1 */ [[Property:P8687]]: 24,445, add reddit sub count
/* wbsetqualifier-add:1| */ [[Property:P585]]: 23 May 2023, update subreddit data
/* wbsetqualifier-add:1| */ [[Property:P407]]: [[Q1860]], update subreddit data
/* wbsetqualifier-add:1| */ [[Property:P580]]: 10 January 2021, update subreddit data
/* wbsetqualifier-add:1| */ [[Property:P1810]]: January 6th, 2021: The Capitol Attack - The day Trump tried to start a civil war, update subreddit data
/* wbsetclaim-create:2||1 */ [[Property:P8032]]: [[Q117229488]]
/* wbsetclaim-create:2||1 */ [[Property:P8032]]: [[Q117229468]]
/* wbsetclaim-create:2||1 */ [[Property:P8032]]: [[Q117229435]]
/* wbsetclaim-create:2||1 */ [[Property:P8032]]: [[Q104709251]]
/* wbsetclaim-update:2||1 */ [[Property:P5582]]: 999
/* wbsetclaim-create:2||1 */ [[Property:P5582]]: 999
/* wbsetaliases-update:26|en */ January 2021 Donald Trump rally, January 2021 United States Capitol protests, storming of the Capitol Building by Donald Trump's supporters, Capitol Building storming, 2021 United States Capitol protests, January 2021 insurrection, Capitol siege, Insurrection of the US Capitol, 2021 U.S. Capitol riot, 2021 United States Capitol attack, Storming of the Capitol, Jan 6 storming of the United States Capitol, January 6 storming of the United States Capitol, January...
/* wbsetaliases-add:1|en-us */ Trump coup attempt
/* wbsetaliases-add:1|en-us */ January 2021 Donald Trump rally
/* wbsetdescription-add:1|en-us */ 2021 mob attempt to prevent or influence Presidential electoral vote count
/* wbsetlabel-add:1|en-us */ 2021 storming of the United States Capitol
/* wbsetaliases-add:1|az */ Konqres Binasına hücum
/* wbsetdescription-add:1|az */ Tramp tərəfdrlarının konqresə hücumu
/* clientsitelink-update:0|enwiki|enwiki:January 6 United States Capitol riot|enwiki:January 6 United States Capitol attack */
/* clientsitelink-update:0|enwiki|enwiki:January 6 United States Capitol attack|enwiki:January 6 United States Capitol riot */
/* wbsetclaim-update:2||1|2 */ [[Property:P8031]]: [[Q109405495]]
/* wbsetaliases-add:1|en */ Trump coup attempt
/* wbeditentity-update-languages-short:0||bn */ add missing labels
/* clientsitelink-update:0|bnwiki|bnwiki:৬ জানুয়ারি,২০২০-এ যুক্তরাষ্ট্রের কংগ্রেসে হামলা|bnwiki:৬ জানুয়ারি,২০২১-এ যুক্তরাষ্ট্রের কংগ্রেসে হামলা */
/* wbsetclaim-update:2||1|2 */ [[Property:P8031]]: [[Q104742053]]
/* wbsetclaim-update:2||1|1 */ [[Property:P8031]]: [[Q104742053]]
/* wbsetclaim-create:2||1 */ [[Property:P8313]]: stormen_på_Kongressen
/* wbsetsitelink-add:1|bnwiki */ ৬ জানুয়ারি,২০২০-এ যুক্তরাষ্ট্রের কংগ্রেসে হামলা
/* clientsitelink-update:0|ptwiki|ptwiki:Invasão do Capitólio dos Estados Unidos em 2021|ptwiki:Ataque ao Capitólio dos Estados Unidos em 2021 */
/* clientsitelink-update:0|zhwiki|zhwiki:2021年美国国会大厦遭冲击事件|zhwiki:2021年美国国会大厦袭击事件 */
/* wbeditentity-update-languages-short:0||pt */
/* clientsitelink-update:0|ukwiki|ukwiki:Штурм Капітолію США 6 січня 2021|ukwiki:Штурм Капітолія США 6 січня 2021 */
/* wbsetclaim-update:2||1 */ [[Property:P5582]]: 950
/* wbsetclaim-create:2||1 */ [[Property:P5582]]: 950
/* wbeditentity-update-languages-short:0||zh */
/* wbsetdescription-set:1|en */ 2021 mob attempt to prevent or influence Presidential electoral vote count, ([[w:en:Wikipedia:Shortdesc helper|Shortdesc helper]])
/* clientsitelink-update:0|zhwiki|zhwiki:2021年美国国会大厦示威|zhwiki:2021年美国国会大厦遭冲击事件 */
/* clientsitelink-update:0|zhwiki|zhwiki:2021年美国国会大厦遭冲击事件|zhwiki:2021年美国国会大厦示威 */
/* undo:0||1774372122|165.155.168.137 */
/* wbsetlabel-set:1|en */ kuttghh
Reverted edits by [[Special:Contributions/79.147.247.3|79.147.247.3]] ([[User talk:79.147.247.3|talk]]) to last revision by [[:User:So9q|So9q]]

In [5]:
#if "label", "alias", "description", "sitelinklink" in comment: look for en/english
wordlist = ["label", "description", "alias", "sitelink"]

#this counts how many comments about labels etc. have no specific language version (possibly multiple languages)
unsure = 0

copied = []

for index, row in df.iterrows():
    
    #skip NaN
    if pd.isna(row["comment"]):
        copied.append(row)
        continue
    
    #include only en-version label/alias/description revisions
    if any(word in row["comment"] for word in wordlist):
        if any(w in row["comment"] for w in ["|en", "English", "english", str("||")]):
            if "||" in row["comment"]:
                unsure +=1
            print("INCLUDE", row["comment"])
            #add this row to new dataframe
            copied.append(row)
        else:
            print("-------------------------- NO ", row["comment"])
    
    else:
        #copy non-label/alias/description revisions
        copied.append(row)
            
print(unsure)

-------------------------- NO  /* wbsetdescription-set:1|de */ gewaltsamer Angriff auf das Kapitol durch Anhänger Donald Trumps am 6. Januar 2021
-------------------------- NO  /* clientsitelink-update:0|shwiki|shwiki:Upad u Kapitol Sjedinjenih Država 6. januara 2021.|shwiki:Napad na Kapitol Sjedinjenih Američkih Država 6. januara */
-------------------------- NO  /* wbsetsitelink-set:1|etwiki */ 2021. aasta rünnak Ameerika Ühendriikide Kapitooliumile
-------------------------- NO  /* wbsetdescription-set:1|ko */ 2021년 1월 6일에 미국 국회의사당에서 대통령 선거인단 투표 집계를 저지하려는 목적으로 발생한 소요사태
-------------------------- NO  /* wbsetlabel-set:1|ko */ 2021년 미국 국회의사당 습격
-------------------------- NO  /* wbsetaliases-add:1|lv */ 6. janvāra uzbrukums ASV Kapitolijam
-------------------------- NO  /* wbsetaliases-add:1|lv */ 2021. gada 6. janvāra uzbrukums ASV Kapitolijam
-------------------------- NO  /* wbsetlabel-add:1|lv */ uzbrukums ASV Kapitolijam
-------------------------- NO  /* wbsetdescription-set:1|pt */ tentativa de golpe de Estado de apoiadores de Donald Trump para impedir ou influenciar a contagem de votos eleitorais presidenciais
-------------------------- NO  /* wbsetaliases-add:1|fr */ assaut du Capitole
INCLUDE /* wbeditentity-update-languages-short:0||tok */ import labels from sitelinks
-------------------------- NO  /* wbsetsitelink-add:1|tokwiki */ jan li utala e tomo lawa pi ma Mewika lon tenpo sike 2021
-------------------------- NO  /* wbsetlabel-set:1|cs */ útok na Kapitol Spojených států amerických (2021)
-------------------------- NO  /* clientsitelink-update:0|cswiki|cswiki:Útok na Kapitol Spojených států amerických 2021|cswiki:Útok na Kapitol Spojených států amerických (2021) */
-------------------------- NO  /* wbsetsitelink-set:1|srwiki */ Јуриш на Капитол Сједињених Америчких Држава 2021.
-------------------------- NO  /* wbsetsitelink-set:1|srwiki */ Протести код Капитола Сједињених Америчких Држава 2021.
-------------------------- NO  /* wbsetaliases-update:2|uk */ штурм будівлі Капітолія прихильниками Дональда Трампа, штурм будівлі Капітолія
-------------------------- NO  /* wbsetlabel-set:1|uk */ Протести в США біля Капітолія 6 січня 2021
INCLUDE /* wbeditentity-update-languages-short:0||kk */ import labels from sitelinks
-------------------------- NO  /* wbsetsitelink-add:1|kkwiki */ АҚШ Капитолийіне шабуыл (2021)
-------------------------- NO  /* wbsetdescription-set:1|vi */ vụ tấn công nhằm ngăn việc chứng nhận bầu cử tổng thống Hoa Kỳ vào ngày 6 tháng 1 năm 2021
-------------------------- NO  /* wbsetlabel-set:1|it */ assalto al Campidoglio degli Stati Uniti d'America del 2021
INCLUDE /* wbsetdescription-set:1|en-us */ 2021 mob attempt to prevent or influence the presidential electoral vote count
-------------------------- NO  /* clientsitelink-update:0|fawiki|fawiki:یورش ۲۰۲۱ به کاخ کنگره ایالات متحده|fawiki:حمله ۶ ژانویه به ساختمان کنگره ایالات متحده آمریکا */
INCLUDE /* clientsitelink-update:0|enwiki|enwiki:January 6 United States Coup attempt by President Donald Trump|enwiki:January 6 United States Capitol attack */
INCLUDE /* clientsitelink-update:0|enwiki|enwiki:January 6 United States Capitol attack|enwiki:January 6 United States Coup attempt by President Donald Trump */
-------------------------- NO  /* clientsitelink-update:0|bnwiki|bnwiki:৬ জানুয়ারি,২০২১-এ যুক্তরাষ্ট্রের কংগ্রেসে হামলা|bnwiki:২০২১ যুক্তরাষ্ট্রের ক্যাপিটলে হামলা */
INCLUDE /* wbsetlabel-set:1|en */ January 6 United States Capitol attack/NRK
INCLUDE /* wbeditentity-update-languages-short:0||ckb */ Updating label from "هێرشکردنە سەر کۆنگرێسی ئەمریکا لەلایەن لایەنگرانی دۆناڵد ترامپ ٢٠٢١" to "ھێرشکردنە سەر کۆنگرێسی ئەمریکا لەلایەن لایەنگرانی دۆناڵد ترامپ"
-------------------------- NO  /* clientsitelink-update:0|wuuwiki|wuuwiki:1月6號國會山襲擊事幹|wuuwiki:国会山骚乱 */
INCLUDE /* wbsetdescription-set:1|en */ 2021 attempt to prevent the U.S. presidential electoral vote count
INCLUDE /* wbsetdescription-set:1|en */ 2021 attempt to prevent presidential electoral vote count
INCLUDE /* wbsetlabeldescriptionaliases:3|en */ January 6 United States Capitol attack, 2021 mob attempt to prevent Presidential electoral vote count, January 2021 United States Capitol protests, storming of the Capitol Building by Donald Trump's supporters, Capitol Building storming, 2021 United States Capitol protests, January 2021 insurrection, Insurrection of the US Capitol, 2021 U.S. Capitol riot, 2021 United States Capitol attack, Storming of the Capitol, Jan 6 storming of the United States Cap...
INCLUDE /* wbeditentity-update-languages-short:0||wuu */ add missing labels
-------------------------- NO  /* clientsitelink-update:0|zh_yuewiki|zh_yuewiki:美國國會大廈衝突|zh_yuewiki:美國國會大廈暴動 */
-------------------------- NO  /* wbsetdescription-add:1|th */ ความสมดุลโลก, #suggestededit-add-desc 1.0
-------------------------- NO  /* wbsetaliases-add:2|zh */ 國會山莊騷亂案, 國會山莊暴動案
-------------------------- NO  /* wbsetaliases-add:4|zh */ 国会山骚乱, 國會山騷亂, 國會山莊騷亂事件, 國會山莊暴動事件
INCLUDE /* wbeditentity-update-languages-short:0||si */ add missing labels
-------------------------- NO  /* wbsetsitelink-add:1|commonswiki */ 2021 storming of the United States Capitol
-------------------------- NO  /* wbsetsitelink-add:1|siwiki */ ජනවාරි 6 එක්සත් ජනපදයේ කැපිටල් ප්‍රහාරය
INCLUDE /* wbsetaliases-update:21|en */ January 2021 United States Capitol protests, storming of the Capitol Building by Donald Trump's supporters, Capitol Building storming, 2021 United States Capitol protests, January 2021 insurrection, Insurrection of the US Capitol, 2021 U.S. Capitol riot, 2021 United States Capitol attack, Storming of the Capitol, Jan 6 storming of the United States Capitol, January 6 storming of the United States Capitol, 1/6/2021, 1/6/21, Capitol Insurrection, January six insu...
INCLUDE /* wbsetdescription-remove:1|en */ 2021 mob attempt to prevent Presidential electoral vote count
INCLUDE /* wbsetlabel-remove:1|en */ 2021 storming of the United States Capitol
-------------------------- NO  /* wbsetlabel-set:1|ar */ اقتحام كابيتول الولايات المتحدة 2021, [[:toollabs:quickstatements/#/batch/223343|batch #223343]]
-------------------------- NO  /* wbsetaliases-add:1|fi */ loppiaiskapina
INCLUDE /* wbeditentity-update-languages-short:0||ki */ add missing labels
-------------------------- NO  /* clientsitelink-update:0|zhwiki|zhwiki:2021年美国国会大厦袭击事件|zhwiki:国会山骚乱 */
-------------------------- NO  /* wbsetdescription-set:1|ru */ попытка демонстрантов в 2021 году предотвратить смену власти в США по итогам выборов 2020 года
-------------------------- NO  /* wbsetlabel-set:1|ru */ захват Капитолия
-------------------------- NO  /* wbsetdescription-add:1|gv */ riftanyn elgyssagh ren soiagh er Ard-whaiyl ny Steatyn Unnaneysit noi eiyrtyssyn y reihys eaghtyraneagh
-------------------------- NO  /* wbsetlabel-add:1|gv */ soiagh er Ard-whaiyl ny Steatyn Unnaneysit
-------------------------- NO  /* wbsetsitelink-add:1|gvwiki */ Soiagh er Ard-whaiyl ny Steatyn Unnaneysit, 2021
INCLUDE /* wbsetdescription-set:1|en */ efforts to stop the certification of Electoral count vote to certify the results of the 2020 U.S. presidential election
-------------------------- NO  /* clientsitelink-update:0|hywiki|hywiki:ԱՄՆ Կապիտոլիումի գրոհում (2021)|hywiki:ԱՄՆ Կապիտոլիումի վրա հարձակում (2021) */
-------------------------- NO  /* wbsetlabel-set:1|sl */ napad na Kapitol Združenih držav Amerike leta 2021
-------------------------- NO  /* wbsetaliases-update:1|sl */ napad na Kapitol
-------------------------- NO  /* wbsetaliases-add:1|sl */ napad na Kaptol
-------------------------- NO  /* wbsetlabel-set:1|sl */ napad na kapitol Združenih držav Amerike leta 2021
-------------------------- NO  /* wbsetlabel-set:1|hu */ az Amerikai Egyesült Államok Capitoliumának ostroma
INCLUDE /* wbsetlabel-set:1|en */ LIES
-------------------------- NO  /* wbsetdescription-add:1|ang */ 2021 folcweallunga tōforhtian preostlice cyneþrymmes weorþscipe rǣd gerihtan
-------------------------- NO  /* wbsetlabel-add:1|ang */ þunorung 2021 oferstigende ðære Unitegan Statum Capitole
INCLUDE /* wbsetdescription-set:1|en */ 2021 mob attempt to prevent Presidential electoral vote count, ([[w:en:Wikipedia:Shortdesc helper|Shortdesc helper]])
-------------------------- NO  /* clientsitelink-update:0|simplewiki|simplewiki:2021 United States Capitol attack|simplewiki:January 6 United States Capitol attack */
INCLUDE /* wbsetaliases-update:26|en */ January 2021 Donald Trump rally, January 2021 United States Capitol protests, storming of the Capitol Building by Donald Trump's supporters, Capitol Building storming, 2021 United States Capitol protests, January 2021 insurrection, Capitol siege, Insurrection of the US Capitol, 2021 U.S. Capitol riot, 2021 United States Capitol attack, Storming of the Capitol, Jan 6 storming of the United States Capitol, January 6 storming of the United States Capitol, January...
INCLUDE /* wbsetaliases-add:1|en-us */ Trump coup attempt
INCLUDE /* wbsetaliases-add:1|en-us */ January 2021 Donald Trump rally
INCLUDE /* wbsetdescription-add:1|en-us */ 2021 mob attempt to prevent or influence Presidential electoral vote count
INCLUDE /* wbsetlabel-add:1|en-us */ 2021 storming of the United States Capitol
-------------------------- NO  /* wbsetaliases-add:1|az */ Konqres Binasına hücum
-------------------------- NO  /* wbsetdescription-add:1|az */ Tramp tərəfdrlarının konqresə hücumu
INCLUDE /* clientsitelink-update:0|enwiki|enwiki:January 6 United States Capitol riot|enwiki:January 6 United States Capitol attack */
INCLUDE /* clientsitelink-update:0|enwiki|enwiki:January 6 United States Capitol attack|enwiki:January 6 United States Capitol riot */
INCLUDE /* wbsetaliases-add:1|en */ Trump coup attempt
INCLUDE /* wbeditentity-update-languages-short:0||bn */ add missing labels
-------------------------- NO  /* clientsitelink-update:0|bnwiki|bnwiki:৬ জানুয়ারি,২০২০-এ যুক্তরাষ্ট্রের কংগ্রেসে হামলা|bnwiki:৬ জানুয়ারি,২০২১-এ যুক্তরাষ্ট্রের কংগ্রেসে হামলা */
-------------------------- NO  /* wbsetsitelink-add:1|bnwiki */ ৬ জানুয়ারি,২০২০-এ যুক্তরাষ্ট্রের কংগ্রেসে হামলা
-------------------------- NO  /* clientsitelink-update:0|ptwiki|ptwiki:Invasão do Capitólio dos Estados Unidos em 2021|ptwiki:Ataque ao Capitólio dos Estados Unidos em 2021 */
-------------------------- NO  /* clientsitelink-update:0|zhwiki|zhwiki:2021年美国国会大厦遭冲击事件|zhwiki:2021年美国国会大厦袭击事件 */
-------------------------- NO  /* clientsitelink-update:0|ukwiki|ukwiki:Штурм Капітолію США 6 січня 2021|ukwiki:Штурм Капітолія США 6 січня 2021 */
INCLUDE /* wbsetdescription-set:1|en */ 2021 mob attempt to prevent or influence Presidential electoral vote count, ([[w:en:Wikipedia:Shortdesc helper|Shortdesc helper]])
-------------------------- NO  /* clientsitelink-update:0|zhwiki|zhwiki:2021年美国国会大厦示威|zhwiki:2021年美国国会大厦遭冲击事件 */
-------------------------- NO  /* clientsitelink-update:0|zhwiki|zhwiki:2021年美国国会大厦遭冲击事件|zhwiki:2021年美国国会大厦示威 */
INCLUDE /* wbsetlabel-set:1|en */ kuttghh
INCLUDE /* wbsetaliases-add:1|en */ January six insurrection
INCLUDE /* wbsetaliases-add:1|en */ 6 January
INCLUDE /* wbsetaliases-add:1|en */ 6th Jan
INCLUDE /* wbsetaliases-add:1|en */ 6 Jan
INCLUDE /* wbsetaliases-add:1|en */ 6th January
-------------------------- NO  /* wbsetaliases-add:1|nl */ bestorming van het Capitool op 6 januari 2021
INCLUDE /* clientsitelink-update:0|enwiki|enwiki:2021 United States Capitol attack|enwiki:January 6 United States Capitol attack */
-------------------------- NO  /* wbsetdescription-set:1|es */ irrupción violenta de partidarios de Donald Trump en el Capitolio de los Estados Unidos
INCLUDE /* wbsetaliases-add:1|en */ Attack on the United States Capitol
INCLUDE /* wbsetaliases-add:1|en */ Capitol Insurrection
-------------------------- NO  /* wbsetdescription-add:1|ko */ 2021년 1월 6일 대통령 선거 인증의 폭력적인 혼란
-------------------------- NO  /* wbsetdescription-add:1|uk */ силовий зрив засвідчення президентських виборів 6 січня 2021 року
INCLUDE /* wbsetaliases-add:1|en */ J6
INCLUDE /* wbsetaliases-add:4|en */ January 6 insurrection, January 6th insurrection, 1/6/2021, 1/6/21
INCLUDE /* wbsetaliases-add:8|en */ January 6th, Jan 6, Jan 6th, Jan. 6, Jan. 6th, Jan 6 storming of the United States Capitol, January 6 storming of the United States Capitol, January 6th storming of the United States Capitol
INCLUDE /* wbsetaliases-add:1|en */ Storming of the Capitol
-------------------------- NO  /* clientsitelink-update:0|eowiki|eowiki:Atako de la Kapitolejo de Usono|eowiki:Atako kontraŭ la Kapitolo de Usono */
INCLUDE /* wbeditentity-update-languages-short:0||ps */ add missing labels
-------------------------- NO  /* wbsetsitelink-add:1|pswiki */ د متحده ایالاتو په کانګرس ماڼۍ د ۲۰۲۱ ز کال برید
INCLUDE /* wbsetlabel-set:1|en-ca */ 2021 storming of the United States Capitol
INCLUDE /* wbsetaliases-add:1|en */ January 6
-------------------------- NO  /* wbsetdescription-set:1|ro */ întrerupere violentă a certificării alegerilor prezidențiale la 6 ianuarie 2021
-------------------------- NO  /* wbsetdescription-set:1|ro */ întrerupere violentă a certificării alegerilor prezidențiale din 6 ianuarie 2021
-------------------------- NO  /* clientsitelink-update:0|idwiki|idwiki:Penyerbuan Gedung Capitol 2021|idwiki:Penyerbuan Gedung Kapitol 2021 */
-------------------------- NO  /* wbsetdescription-set:1|it */ tentativo di insurrezione a Washington D.C., avvenuto il 6 gennaio 2021
-------------------------- NO  /* wbsetdescription-set:1|it */ insurrezione accaduta a Washington D.C. il 6 gennaio 2021
INCLUDE /* clientsitelink-update:0|enwikiquote|enwikiquote:2021 storming of the United States Capitol|enwikiquote:2021 United States Capitol attack */
-------------------------- NO  /* clientsitelink-update:0|eowiki|eowiki:Sturmo de la Kapitolo de Usono|eowiki:Atako de la Kapitolejo de Usono */
-------------------------- NO  /* wbsetdescription-set:1|es */ irrupción de partidarios del expresidente Trump en el Capitolio de los Estados Unidos
-------------------------- NO  /* clientsitelink-update:0|ckbwiki|ckbwiki:ھێرشکردنە سەر کۆنگرێسی ئەمریکا لەلایەن لایەنگرانی دۆناڵد ترامپ ٢٠٢١|ckbwiki:ھێرشکردنە سەر کۆنگرێسی ئەمریکا لەلایەن لایەنگرانی دۆناڵد ترامپ (٢٠٢١) */
INCLUDE /* wbsetdescription-set:1|en */ violent disruption of the presidential election certification on January 6, 2021
-------------------------- NO  /* wbsetdescription-add:1|af */ Geweldadige ontwrigting van die presidensiële sertifisering op 6 Januarie 2021
-------------------------- NO  /* wbsetlabel-set:1|af */ Bestorming van die Verenigde State Kongresgebou in 2021
INCLUDE /* wbsetaliases-add:1|en */ 2021 U.S. Capitol riot
-------------------------- NO  /* wbsetdescription-set:1|ru */ Захват Солнечного парка
-------------------------- NO  /* clientsitelink-update:0|simplewiki|simplewiki:2021 storming of the United States Capitol|simplewiki:2021 United States Capitol attack */
-------------------------- NO  /* wbsetsitelink-set-both:2|nowiki */ Stormingen av den amerikanske kongressen 2021, [[Q17437798]]
-------------------------- NO  /* wbsetaliases-remove:3|nl */ bestorming van het Capitool voor Trump, bestorming van het Capitool op 6 januari, bestorming van het Amerikaanse Capitool op 6 januari
INCLUDE /* clientsitelink-update:0|enwiki|enwiki:2021 storming of the United States Capitol|enwiki:2021 United States Capitol attack */
-------------------------- NO  /* clientsitelink-update:0|cywiki|cywiki:Y cyrch ar Gapitol yr Unol Daleithiau 2021|cywiki:Y cyrch ar Gapitol yr Unol Daleithiau (2021) */
INCLUDE /* clientsitelink-update:0|enwiki|enwiki:2021 United States Capitol attack|enwiki:2021 storming of the United States Capitol */
INCLUDE /* clientsitelink-update:0|enwiki|enwiki:2021 storming of the United States Capitol|enwiki:2021 United States Capitol attack */
INCLUDE /* clientsitelink-update:0|enwiki|enwiki:2021 United States Capitol attack|enwiki:2021 storming of the United States Capitol */
-------------------------- NO  /* clientsitelink-update:0|bswiki|bswiki:Protestno zauzimanje Kapitola Sjedinjenih Američkih Država 2021.|bswiki:Napad na Kapitol Sjedinjenih Američkih Država 2021. */
-------------------------- NO  /* wbsetdescription-add:1|is */ Valdaránstilraun 6. janúar 2021
-------------------------- NO  /* clientsitelink-update:0|zhwiki|zhwiki:2021年美国国会大厦攻擊事件|zhwiki:2021年美国国会大厦遭冲击事件 */
-------------------------- NO  /* clientsitelink-update:0|zhwiki|zhwiki:2021年美国国会大厦遭冲击事件|zhwiki:2021年美国国会大厦攻擊事件 */
INCLUDE /* wbsetsitelink-add:1|enwiki */ 2021 United States Capitol attack
INCLUDE /* wbsetsitelink-remove:1|enwiki */ 2021 storming of the United States Capitol
-------------------------- NO  /* clientsitelink-update:0|fawiki|fawiki:حمله به کاخ کنگره ایالات متحده|fawiki:یورش ۲۰۲۱ به کاخ کنگره ایالات متحده */
-------------------------- NO  /* wbsetsitelink-add:1|jawikinews */ アメリカ議会議事堂 トランプ大統領支持者によって占拠される
INCLUDE /* wbeditentity-update-languages-short:0||sr */ add missing labels
-------------------------- NO  /* wbsetsitelink-add:1|srwiki */ Јуриш на Капитол Сједињених Америчких Држава 2021.
-------------------------- NO  /* wbsetsitelink-remove:1|bgwiki */ Щурм на Капитолия
INCLUDE /* wbeditentity-update-languages-short:0||fy */ add missing labels
-------------------------- NO  /* wbsetsitelink-add:1|fywiki */ Bestoarming fan it Amerikaanske Kapitoal (2021)
-------------------------- NO  /* wbsetdescription-set:1|ja */ 2021年1月6日に発生した暴力的な混乱
-------------------------- NO  /* clientsitelink-update:0|fawiki|fawiki:حمله به کاخ کنگره ایالات متحده (۲۰۲۱)|fawiki:حمله به کاخ کنگره ایالات متحده */
-------------------------- NO  /* wbsetaliases-add:1|zh */ 2021年冲击美国国会大厦事件
-------------------------- NO  /* wbsetlabel-set:1|zh */ 2021年美国国会大厦遭冲击事件
-------------------------- NO  /* clientsitelink-update:0|afwiki|afwiki:Bestorming van die Verenigde State Capitol in 2021|afwiki:Bestorming van die Verenigde State Kongresgebou in 2021 */
-------------------------- NO  /* wbsetdescription-add:1|da */ Terrorangreb
-------------------------- NO  /* wbsetaliases-update:1|is */ mótmælin í Bandaríkjaþinghúsinu 2021
-------------------------- NO  /* wbsetlabel-set:1|wa */ assôt do Capitål
-------------------------- NO  /* wbsetlabel-set:1|is */ árásin á Bandaríkjaþing 2021
INCLUDE /* wbsetaliases-add:2|en */ Capitol siege, Insurrection of the US Capitol
-------------------------- NO  /* wbsetdescription-set:1|it */ tentato colpo di Stato dei sostenitori di Trump contro il legittimo risultato elettorale
-------------------------- NO  /* wbsetdescription-set:1|es */ partidarios incontrolados del ex-presidente estadounidense Donald Trump irrumpieron en el Capitolio de los Estados Unidos
-------------------------- NO  /* wbsetdescription-set:1|es */ partidarios incontrolados del ex-presidente estadounidense, Donald Trump irrumpieron en el Capitolio de los Estados Unidos
-------------------------- NO  /* wbsetdescription-set:1|es */ partidarios incontrolados del ex-presidente estadounidense, Donald Trump, irrumpieron en el Capitolio de los Estados Unidos
-------------------------- NO  /* wbsetdescription-set:1|es */ partidarios del ex-Presidente de los Estados Unidos, Donald J. Trump, irrumpieron en el Capitolio de los Estados Unidos
-------------------------- NO  /* wbsetdescription-add:1|es */ acontecimiento ocurrido el 6 de enero de 2021, cuando partidarios del ex-presidente de los Estados Unidos, Donald Trump, irrumpieron en la sede del Congreso y el Senado de los Estados Unidos
INCLUDE /* wbsetaliases-add:1|en */ January 2021 insurrection
-------------------------- NO  /* clientsitelink-update:0|ckbwiki|ckbwiki:هێرشکردنە سەر کۆنگرێسی ئەمریکا لەلایەن لایەنگرانی دۆناڵد ترامپ ٢٠٢١|ckbwiki:ھێرشکردنە سەر کۆنگرێسی ئەمریکا لەلایەن لایەنگرانی دۆناڵد ترامپ ٢٠٢١ */
INCLUDE /* wbsetsitelink-remove:1|enwikiquote */ 2021 storming of the United States Capitol
INCLUDE /* clientsitelink-update:0|enwiki|enwiki:Storming of the United States Capitol|enwiki:2021 storming of the United States Capitol */

In [6]:
copied_df = pd.DataFrame(copied)

copied_df.head(10)

,revid,parentid,user,timestamp,size,comment,anon,minor,commenthidden,userhidden,suppressed
0,2504691802,2503966829,Vicarage,2026-06-11T17:20:01Z,167005,/* wbremoveclaims-remove:1| */ [[Property:P625...,NaN,NaN,NaN,NaN,NaN
1,2503966829,2503943744,Vicarage,2026-06-09T21:04:25Z,167520,/* undo:0||2503647430|Quesotiotyo */ Events cl...,NaN,NaN,NaN,NaN,NaN
2,2503943744,2503647430,Pi bot,2026-06-09T20:04:46Z,167005,/* wbsetclaim-create:2||1 */ [[Property:P625]]...,NaN,NaN,NaN,NaN,NaN
3,2503647430,2500170824,Quesotiotyo,2026-06-09T06:11:24Z,166474,/* wbremoveclaims-remove:1| */ [[Property:P625...,NaN,NaN,NaN,NaN,NaN
4,2500170824,2499912567,Twofivesixbot,2026-05-31T15:55:23Z,167006,/* wbsetclaim-update-qualifiers:1||1|2 */ [[Pr...,NaN,NaN,NaN,NaN,NaN
6,2483947620,2478517786,VGMaintenanceBot,2026-04-22T17:20:29Z,166369,/* wbsetqualifier-add:1| */ [[Property:P9675]]...,NaN,NaN,NaN,NaN,NaN
14,2460817388,2460816772,Peaceray,2026-02-05T06:35:04Z,165699,/* wbsetclaim-update:2||1|1 */ [[Property:P524...,NaN,NaN,NaN,NaN,NaN
15,2460816772,2460816710,Peaceray,2026-02-05T06:31:05Z,164423,/* wbsetclaim-update:2||1|1 */ [[Property:P803...,NaN,NaN,NaN,NaN,NaN
16,2460816710,2460816545,Peaceray,2026-02-05T06:30:54Z,162016,/* wbsetclaim-update:2||1|1 */ [[Property:P803...,NaN,NaN,NaN,NaN,NaN
17,2460816545,2460816178,Peaceray,2026-02-05T06:30:14Z,159609,/* wbsetclaim-update:2||1|1 */ [[Property:P803...,NaN,NaN,NaN,NaN,NaN

In [7]:
#format timestamp, divide anonymous users and registered

copied_df["timestamp"] = pd.to_datetime(copied_df["timestamp"])
copied_df["minor_edit"] = copied_df.get("minor", pd.Series(False, index=copied_df.index)).notna()
copied_df["anonymous"] = copied_df["user"].str.match(
    r"^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$",
    na=False
)
copied_df = copied_df.sort_values("timestamp", ascending=True)
display(copied_df.head())

,revid,parentid,user,timestamp,size,comment,anon,minor,commenthidden,userhidden,suppressed,minor_edit,anonymous
1017,1336126283,0,Taavi,2021-01-06 19:49:47+00:00,393,/* wbeditentity-create:2|en */ January 2021 Do...,NaN,NaN,NaN,NaN,NaN,False,False
1016,1336126517,1336126283,Taavi,2021-01-06 19:50:16+00:00,506,/* wbmergeitems-from:0||Q104705421 */ [[MediaW...,NaN,NaN,NaN,NaN,NaN,False,False
1015,1336126684,1336126517,Taavi,2021-01-06 19:50:37+00:00,935,/* wbsetclaim-create:2||1 */ [[Property:P31]]:...,NaN,NaN,NaN,NaN,NaN,False,False
1014,1336126841,1336126684,Taavi,2021-01-06 19:51:02+00:00,1453,/* wbsetclaim-create:2||1 */ [[Property:P585]]...,NaN,NaN,NaN,NaN,NaN,False,False
1013,1336126893,1336126841,Taavi,2021-01-06 19:51:09+00:00,1954,/* wbsetclaim-create:2||1 */ [[Property:P585]]...,NaN,NaN,NaN,NaN,NaN,False,False

In [8]:
#add filtering function
def filter_revisions(
    df,
    user=None,
    start_date=None,
    end_date=None,
    comment_contains=None,
    exclude_bot=None,
    anonymous_only=False,
    registered_only=False
):
    result = df.copy()

    if user:
        result = result[
            result["user"].str.contains(user, case=False, na=False)
        ]

    if start_date:
        result = result[
            result["timestamp"] >= pd.to_datetime(start_date)
        ]

    if end_date:
        result = result[
            result["timestamp"] <= pd.to_datetime(end_date)
        ]

    if comment_contains:
        result = result[
            result["comment"].str.contains(
                comment_contains,
                case=False,
                na=False
            )
        ]
        
    if exclude_bot:
        result = result[
            ~result["user"].str.contains("bot", case=False, na=False)
        ]

    if anonymous_only:
        result = result[result["anonymous"]]
    
    if registered_only:
        result = result[~result["anonymous"]]

    return result

In [9]:
#exclude anonymous users and bots (through username - not a perfect way of doing this, inspired by manual sanity checks of revision history)
non_anon_edits = filter_revisions(
    copied_df,
    registered_only=True,
    exclude_bot=True
)

display(non_anon_edits.head(30))
print(len(non_anon_edits))

,revid,parentid,user,timestamp,size,comment,anon,minor,commenthidden,userhidden,suppressed,minor_edit,anonymous
1017,1336126283,0,Taavi,2021-01-06 19:49:47+00:00,393,/* wbeditentity-create:2|en */ January 2021 Do...,NaN,NaN,NaN,NaN,NaN,False,False
1016,1336126517,1336126283,Taavi,2021-01-06 19:50:16+00:00,506,/* wbmergeitems-from:0||Q104705421 */ [[MediaW...,NaN,NaN,NaN,NaN,NaN,False,False
1015,1336126684,1336126517,Taavi,2021-01-06 19:50:37+00:00,935,/* wbsetclaim-create:2||1 */ [[Property:P31]]:...,NaN,NaN,NaN,NaN,NaN,False,False
1014,1336126841,1336126684,Taavi,2021-01-06 19:51:02+00:00,1453,/* wbsetclaim-create:2||1 */ [[Property:P585]]...,NaN,NaN,NaN,NaN,NaN,False,False
1013,1336126893,1336126841,Taavi,2021-01-06 19:51:09+00:00,1954,/* wbsetclaim-create:2||1 */ [[Property:P585]]...,NaN,NaN,NaN,NaN,NaN,False,False
1011,1336126941,1336126925,Galaktos,2021-01-06 19:51:16+00:00,2505,/* wbsetclaim-create:2||1 */ [[Property:P17]]:...,NaN,NaN,NaN,NaN,NaN,False,False
1010,1336127004,1336126941,Galaktos,2021-01-06 19:51:25+00:00,2928,/* wbsetclaim-create:2||1 */ [[Property:P276]]...,NaN,NaN,NaN,NaN,NaN,False,False
1009,1336127296,1336127004,Taavi,2021-01-06 19:52:08+00:00,3344,/* wbsetclaim-create:2||1 */ [[Property:P276]]...,NaN,NaN,NaN,NaN,NaN,False,False
1008,1336127696,1336127296,Galaktos,2021-01-06 19:53:02+00:00,3781,/* wbsetclaim-create:2||1 */ [[Property:P1269]...,NaN,NaN,NaN,NaN,NaN,False,False
1007,1336127758,1336127696,Taavi,2021-01-06 19:53:11+00:00,4219,/* wbsetclaim-create:2||1 */ [[Property:P361]]...,NaN,NaN,NaN,NaN,NaN,False,False
1006,1336127789,1336127758,Galaktos,2021-01-06 19:53:15+00:00,4219,/* wbsetclaim-update:2||1 */ [[Property:P1269]...,NaN,NaN,NaN,NaN,NaN,False,False
1003,1336137788,1336135783,Numberguy6,2021-01-06 20:17:49+00:00,4525,/* clientsitelink-update:0|enwiki|enwiki:Janua...,NaN,NaN,NaN,NaN,NaN,False,False
1002,1336138132,1336137788,Zuiarra,2021-01-06 20:18:44+00:00,4521,/* wbsetclaim-update:2||1 */ [[Property:P276]]...,NaN,NaN,NaN,NaN,NaN,False,False
998,1336141800,1336140591,Numberguy6,2021-01-06 20:28:22+00:00,4937,/* wbsetlabel-set:1|en */ January 2021 United ...,NaN,NaN,NaN,NaN,NaN,False,False
997,1336141805,1336141800,Numberguy6,2021-01-06 20:28:23+00:00,5037,/* wbsetaliases-add:1|en */ January 2021 Donal...,NaN,NaN,NaN,NaN,NaN,False,False
995,1336142516,1336142207,Natg 19,2021-01-06 20:30:21+00:00,5164,/* clientsitelink-update:0|enwiki|enwiki:Janua...,NaN,NaN,NaN,NaN,NaN,False,False
994,1336143113,1336142516,J 1982,2021-01-06 20:32:03+00:00,5164,/* wbeditentity-update:0| */ Changing order of...,NaN,NaN,NaN,NaN,NaN,False,False
991,1336149678,1336146989,Thierry Caro,2021-01-06 20:43:47+00:00,5738,/* wbsetclaim-create:2||1 */ [[Property:P527]]...,NaN,NaN,NaN,NaN,NaN,False,False
987,1336153933,1336152369,Nintendofan885,2021-01-06 20:49:44+00:00,6410,/* wbsetclaim-create:2||1 */ [[Property:P580]]...,NaN,NaN,NaN,NaN,NaN,False,False
986,1336153983,1336153933,Nintendofan885,2021-01-06 20:49:48+00:00,5909,/* wbremoveclaims-remove:1| */ [[Property:P585...,NaN,NaN,NaN,NaN,NaN,False,False
985,1336154007,1336153983,Nintendofan885,2021-01-06 20:49:50+00:00,5391,/* wbremoveclaims-remove:1| */ [[Property:P585...,NaN,NaN,NaN,NaN,NaN,False,False
946,1336190320,1336188793,Numberguy6,2021-01-06 21:42:01+00:00,8070,/* wbsetlabel-set:1|en */ 2021 United States C...,NaN,NaN,NaN,NaN,NaN,False,False
945,1336190345,1336190320,Numberguy6,2021-01-06 21:42:02+00:00,8167,/* wbsetaliases-add:1|en */ January 2021 Unite...,NaN,NaN,NaN,NaN,NaN,False,False
911,1336245221,1336244296,Peaceray,2021-01-06 22:48:40+00:00,10448,/* wbsetclaim-create:2||1 */ [[Property:P1339]...,NaN,NaN,NaN,NaN,NaN,False,False
909,1336246266,1336245265,Silsha,2021-01-06 22:50:27+00:00,10297,/* wbsetclaim-update:2||1 */ [[Property:P1339]...,NaN,NaN,NaN,NaN,NaN,False,False
906,1336247847,1336247222,Peaceray,2021-01-06 22:53:02+00:00,11193,/* wbsetclaim-create:2||1 */ [[Property:P5582]...,NaN,NaN,NaN,NaN,NaN,False,False
904,1336248757,1336248564,Peaceray,2021-01-06 22:54:30+00:00,11627,/* wbcreateclaim-create:1| */ [[Property:P664]...,NaN,NaN,NaN,NaN,NaN,False,False
903,1336249466,1336248757,Peaceray,2021-01-06 22:55:40+00:00,12589,/* wbsetclaim-update:2||1|2 */ [[Property:P664...,NaN,NaN,NaN,NaN,NaN,False,False
902,1336250044,1336249466,Peaceray,2021-01-06 22:56:33+00:00,13440,/* wbsetclaim-create:2||1 */ [[Property:P664]]...,NaN,NaN,NaN,NaN,NaN,False,False
901,1336256927,1336250044,Silsha,2021-01-06 23:08:08+00:00,14301,/* wbsetclaim-create:2||1 */ [[Property:P1120]...,NaN,NaN,NaN,NaN,NaN,False,False

483

In [10]:
#get unique users
unique_users = non_anon_edits["user"].dropna().unique()

print(f"Total distinct users: {len(unique_users)}\n")

for u in unique_users:
    print(u)

Total distinct users: 119

Taavi
Galaktos
Numberguy6
Zuiarra
Natg 19
J 1982
Thierry Caro
Nintendofan885
Peaceray
Silsha
Marcus Cyron
LennBr
Iconicos
Triggerhippie4
AleatoryPonderings
PtiBzh
CaptainEek
Bravetheif
Evolutionoftheuniverse
KajenCAT
Coffins
Ottawajin
Nachtbold
1857a
Harej
2600:1702:6A0:8540:75DB:CC5:DE88:C9DD
LLs
Superbia23
Koavf
JhowieNitnek
Ctruongngoc
ABPMAB
Rp2006
Paracel63
Kooma
Airon90
Mxn
Wd-Ryan
TnT20052013
Entbert
NMaia
2601:151:C301:33F0:80A0:8994:8580:D1D2
Trivialist
Mannivu
MareBG
Maxlath
2603:7080:1A49:C900:65BF:7C7F:1AC8:575
ViktorQT
Martin Urbanec
Ralf Roletschek
Sänger
Gwennie-nyan
Y2kcrazyjoker4
2601:19B:801:3120:C852:7D9:60BC:2272
Anthony Appleyard
Elli
Rosguill
Aseleste
2601:58C:100:78F0:E58B:49B0:CAD0:8E9B
CmdrDan
Jane023
Belteshassar
Red Slash
Somedifferentstuff
Aoidh
Trygve W Nodeland
Yupik
MelanieN
Pacostein
Geo Swan
2600:1700:8841:D160:780A:795D:B829:A972
Andrew Gray
Kalki
Erik den yngre
TheWxResearcher
Eurohunter
Nivamp
04anotherghost
Ikkingjinnammebetinke
Rural City
Geagea
Dekimasu
So9q
Ffffrr
小林子冲
C960657
Deansfa
CarmenEsparzaAmoux
Vozul
Iamahumanborninearth
VQuakr
En Merker
Sofie Geneea
Tm
Horcrux
Johshh
Quesotiotyo
Sinatrasona
Stylez995
2601:602:D000:FFA0:71E1:7D36:9602:3C12
Roshkara
علاء
Matěj Suchánek
2601:644:907E:A450:A5E1:78E5:F367:2700
白殕毛
Šaholjubac
Ham II
Qwerty786
Rhododendrites
Jock64
Pyb en résidence
2603:7080:29F0:8ED0:E90F:FAA5:1AED:4BA5
2A01:9700:9130:3700:C474:5DE3:3B1B:44EC
Trade
Girligaanshub
UndefinedRachel
Doug Grinbergs
DanGFSouza
Vicarage

In [11]:
user_counts = non_anon_edits["user"].value_counts()

print(f"total distinct users: {len(user_counts)}\n")

print(user_counts.head(50))

total distinct users: 119

user
Peaceray                                   69
Triggerhippie4                             54
Thierry Caro                               39
2603:7080:1A49:C900:65BF:7C7F:1AC8:575     28
AleatoryPonderings                         27
2600:1700:8841:D160:780A:795D:B829:A972    21
Nintendofan885                             14
Wd-Ryan                                    11
Ottawajin                                   9
2600:1702:6A0:8540:75DB:CC5:DE88:C9DD       8
Bravetheif                                  7
Taavi                                       7
Numberguy6                                  7
JhowieNitnek                                6
Galaktos                                    6
Yupik                                       6
Nivamp                                      5
Silsha                                      5
KajenCAT                                    4
En Merker                                   4
Geo Swan                                    4
Kooma                                       4
CmdrDan                                     3
Ralf Roletschek                             3
Pacostein                                   3
PtiBzh                                      3
2601:602:D000:FFA0:71E1:7D36:9602:3C12      3
Doug Grinbergs                              3
Ham II                                      3
علاء                                        3
Trivialist                                  3
Ikkingjinnammebetinke                       3
Vicarage                                    2
Matěj Suchánek                              2
Johshh                                      2
Quesotiotyo                                 2
Stylez995                                   2
Horcrux                                     2
1857a                                       2
LLs                                         2
Harej                                       2
Airon90                                     2
Deansfa                                     2
TnT20052013                                 2
Ffffrr                                      2
04anotherghost                              2
Andrew Gray                                 2
Belteshassar                                2
Sänger                                      2
Martin Urbanec                              2
Name: count, dtype: int64

In [12]:
#sort by time and show number of edits

cutoff = pd.Timestamp("2026-01-10", tz="UTC")
before_cutoff = non_anon_edits[non_anon_edits["timestamp"]<cutoff]
summary = pd.DataFrame({
    "edit_count": before_cutoff["user"].value_counts(),
    "latest_revision": before_cutoff.groupby("user")["timestamp"].max()
})

summary = summary.sort_values(
    "latest_revision",
    ascending=False
)

print(summary.head(50))

                                         edit_count           latest_revision
user
Doug Grinbergs                                    3 2026-01-07 05:21:21+00:00
DanGFSouza                                        1 2025-12-24 13:56:47+00:00
UndefinedRachel                                   1 2025-11-14 17:08:59+00:00
Girligaanshub                                     2 2025-09-16 16:02:06+00:00
Trade                                             1 2025-05-25 19:32:51+00:00
Kooma                                             4 2025-01-21 17:23:39+00:00
2A01:9700:9130:3700:C474:5DE3:3B1B:44EC           1 2025-01-20 18:38:23+00:00
2603:7080:29F0:8ED0:E90F:FAA5:1AED:4BA5           1 2024-12-25 18:27:28+00:00
Pyb en résidence                                  1 2024-12-15 23:12:16+00:00
Jock64                                            1 2024-12-13 00:26:18+00:00
Rhododendrites                                    1 2024-10-17 00:44:37+00:00
Qwerty786                                         1 2024-10-16 23:39:11+00:00
Wd-Ryan                                          11 2024-10-07 00:11:11+00:00
Matěj Suchánek                                    2 2024-08-30 20:39:36+00:00
Ham II                                            3 2024-08-09 15:13:34+00:00
علاء                                              3 2024-08-02 19:51:56+00:00
Šaholjubac                                        1 2024-07-20 14:00:30+00:00
白殕毛                                               1 2024-07-16 18:29:21+00:00
2601:644:907E:A450:A5E1:78E5:F367:2700            1 2024-07-01 17:35:12+00:00
Roshkara                                          1 2024-02-05 00:29:36+00:00
2601:602:D000:FFA0:71E1:7D36:9602:3C12            3 2024-02-04 23:43:37+00:00
Stylez995                                         2 2024-01-16 09:04:08+00:00
Peaceray                                         47 2024-01-06 23:52:30+00:00
Sinatrasona                                       1 2024-01-06 07:51:48+00:00
Quesotiotyo                                       1 2023-12-29 21:22:32+00:00
Sänger                                            2 2023-12-07 05:16:36+00:00
Johshh                                            2 2023-11-29 11:59:48+00:00
Horcrux                                           2 2023-10-07 13:50:11+00:00
Tm                                                1 2023-07-19 17:48:42+00:00
Ffffrr                                            2 2023-07-09 03:45:06+00:00
Nintendofan885                                   14 2023-03-20 23:04:33+00:00
Sofie Geneea                                      1 2023-03-06 14:52:08+00:00
En Merker                                         4 2023-03-06 13:36:06+00:00
VQuakr                                            1 2023-03-03 08:00:35+00:00
Iamahumanborninearth                              1 2023-03-03 07:33:39+00:00
Vozul                                             1 2023-02-26 00:21:55+00:00
CarmenEsparzaAmoux                                1 2023-02-16 20:18:54+00:00
Deansfa                                           2 2023-01-23 23:08:06+00:00
C960657                                           1 2023-01-17 20:24:05+00:00
04anotherghost                                    2 2023-01-10 00:10:23+00:00
小林子冲                                              1 2022-12-29 00:34:50+00:00
Andrew Gray                                       2 2022-11-08 19:36:44+00:00
So9q                                              1 2022-10-29 03:21:19+00:00
Nivamp                                            5 2022-10-05 16:55:30+00:00
Dekimasu                                          1 2022-08-12 15:07:09+00:00
Ikkingjinnammebetinke                             3 2022-07-25 10:58:47+00:00
Geagea                                            1 2022-07-19 09:49:51+00:00
Trivialist                                        3 2022-07-02 16:52:56+00:00
Rural City                                        1 2022-06-16 07:04:56+00:00
Eurohunter                                        1 2022-02-12 11:19:05+00:00

We selected a pool of candidates by looking at recent human contributors and contributors with a lot of edits in the past. We verified the users' pages on Wikidata to make sure they were still (somewhat) active. We verified the revision history manually to confirm that their edits were not only administratory tasks but added/removed/modified content of the item page